"""
on_chain/submit_audit.py — Submit AI analysis hash to Mantle Sepolia AuditLog contract.

Hash is keccak256(deterministic JSON of the analysis output).
JSON uses sort_keys=True and no whitespace for reproducibility.
The hash commits to the exact verdict, confluence count, and pre-trade note
that was generated by the agents — proving it was made at a specific block timestamp.

Judges can verify: recompute the hash from the displayed analysis and compare to on-chain.
"""

import os
import json
import logging
from typing import Optional
from datetime import datetime, timezone

from web3 import Web3
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)

# ── Contract configuration ────────────────────────────────────────────────────

PRIVATE_KEY     = os.getenv("PRIVATE_KEY", "")
DEPLOYMENT_FILE = os.path.join(os.path.dirname(__file__), "deployment.json")

# Multiple Mantle Sepolia RPCs tried in order — single RPC is a demo-killer
_MANTLE_SEPOLIA_RPCS = [
    os.getenv("MANTLE_SEPOLIA_RPC", ""),
    "https://rpc.sepolia.mantle.xyz",
    "https://mantle-sepolia.drpc.org",
    "https://endpoints.omniatech.io/v1/mantle/sepolia/public",
]


def _get_w3() -> Web3:
    """Return connected Web3 to Mantle Sepolia, trying fallback RPCs."""
    for rpc in _MANTLE_SEPOLIA_RPCS:
        if not rpc:
            continue
        try:
            w3 = Web3(Web3.HTTPProvider(rpc, request_kwargs={"timeout": 15}))
            w3.eth.block_number   # connectivity test
            return w3
        except Exception:
            continue
    raise ConnectionError("All Mantle Sepolia RPC endpoints failed")

# Full ABI — matches TradingSignalOracle v2 (AuditLog.sol)
AUDIT_LOG_ABI = [
    {
        "inputs": [
            {"internalType": "string",  "name": "symbol",          "type": "string"},
            {"internalType": "bytes32", "name": "dataHash",         "type": "bytes32"},
            {"internalType": "string",  "name": "verdict",          "type": "string"},
            {"internalType": "uint8",   "name": "confidence",       "type": "uint8"},
            {"internalType": "uint8",   "name": "confluenceCount",  "type": "uint8"},
            {"internalType": "string",  "name": "scenario",         "type": "string"},
        ],
        "name": "logAnalysis",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [
            {"internalType": "string", "name": "symbol",          "type": "string"},
            {"internalType": "string", "name": "verdict",         "type": "string"},
            {"internalType": "string", "name": "macroRegime",     "type": "string"},
            {"internalType": "uint8",  "name": "confidence",      "type": "uint8"},
            {"internalType": "uint8",  "name": "confluenceCount", "type": "uint8"},
            {"internalType": "string", "name": "scenario",        "type": "string"},
        ],
        "name": "updateSignal",
        "outputs": [],
        "stateMutability": "nonpayable",
        "type": "function",
    },
    {
        "inputs": [{"internalType": "string", "name": "symbol", "type": "string"}],
        "name": "getLatestSignal",
        "outputs": [
            {"internalType": "string",  "name": "verdict",         "type": "string"},
            {"internalType": "string",  "name": "macroRegime",     "type": "string"},
            {"internalType": "uint8",   "name": "confidence",      "type": "uint8"},
            {"internalType": "uint8",   "name": "confluenceCount", "type": "uint8"},
            {"internalType": "uint256", "name": "updatedAt",       "type": "uint256"},
            {"internalType": "bool",    "name": "exists",          "type": "bool"},
        ],
        "stateMutability": "view",
        "type": "function",
    },
    {
        "anonymous": False,
        "inputs": [
            {"indexed": True,  "name": "submitter",      "type": "address"},
            {"indexed": False, "name": "symbol",         "type": "string"},
            {"indexed": False, "name": "dataHash",       "type": "bytes32"},
            {"indexed": False, "name": "verdict",        "type": "string"},
            {"indexed": False, "name": "confidence",     "type": "uint8"},
            {"indexed": False, "name": "confluenceCount","type": "uint8"},
            {"indexed": False, "name": "scenario",       "type": "string"},
            {"indexed": False, "name": "blockTimestamp", "type": "uint256"},
        ],
        "name": "AnalysisLogged",
        "type": "event",
    },
    {
        "inputs": [],
        "name": "version",
        "outputs": [{"internalType": "string", "name": "", "type": "string"}],
        "stateMutability": "pure",
        "type": "function",
    },
]


# ── Hash computation ──────────────────────────────────────────────────────────

def build_hashable_payload(result: dict) -> dict:
    """
    Build the deterministic dict that gets hashed and stored on-chain.
    Timestamp is rounded to the nearest minute for reproducibility within a
    1-minute window (avoids sub-second differences invalidating the hash).

    Judges can re-run this on the displayed analysis to verify the hash matches.
    """
    ts = result.get("timestamp_utc", "")
    ts_rounded = ts[:16] + ":00Z" if len(ts) >= 16 else ts   # round to minute

    analysis = result.get("analysis", {})
    macro    = result.get("macro_regime", {})

    return {
        "symbol":              result["symbol"],
        "analysis_timestamp_utc_minute": ts_rounded,
        "scenario":            f"S{result.get('scenario_number')}_{result.get('scenario_name', '')}",
        "cvd_matrix_state":    result.get("cvd_matrix_state"),
        "macro_regime":        macro.get("macro_regime"),
        "verdict":             analysis.get("verdict"),
        "confidence_score":    analysis.get("confidence_score"),
        "confluence_count":    analysis.get("confluence_count"),
        "entry_trigger":       analysis.get("entry_trigger"),
        "stop_price":          analysis.get("stop_price"),
        "target_1":            analysis.get("target_1"),
        "leverage_recommended":analysis.get("leverage_recommended"),
        "pre_trade_note_why":  analysis.get("pre_trade_note_why"),
        "pre_trade_note_wrong":analysis.get("pre_trade_note_wrong"),
        "pre_trade_note_add":  analysis.get("pre_trade_note_add"),
        "failure_mode":        analysis.get("failure_mode"),
        "playbook_rules_cited":sorted(analysis.get("playbook_rules_cited", [])),
        # Dual hash: snapshot_hash commits to the INPUT data the system SAW
        # Any judge can verify both what the AI said AND what it saw when it said it
        "snapshot_hash":       result.get("snapshot_hash"),
        "base_direction":      result.get("base_direction"),
        "verdict_overridden":  analysis.get("verdict_overridden", False),
        "confidence_calibrated": analysis.get("confidence_calibrated", False),
        # Playbook version fingerprint — ties this recommendation to exact prompt version
        "playbook_prompt_hash": _get_prompt_version_hash(),
    }


def _get_prompt_version_hash() -> str:
    """Returns a short fingerprint of the current prompt content."""
    try:
        from agents.prompts import MACRO_REGIME_PROMPT, FULL_ANALYSIS_PROMPT
        combined = MACRO_REGIME_PROMPT + FULL_ANALYSIS_PROMPT
        return Web3.keccak(text=combined).hex()[:16]
    except Exception:
        return "unavailable"


def compute_hash(result: dict) -> tuple[str, str]:
    """
    Returns (hex_hash, json_payload_string).
    hex_hash:        '0x...' keccak256, 32 bytes — what goes on-chain
    json_payload:    deterministic JSON string — what judges use to verify
    """
    payload      = build_hashable_payload(result)
    payload_json = json.dumps(payload, sort_keys=True, separators=(',', ':'))
    hash_bytes   = Web3.keccak(text=payload_json)
    return hash_bytes.hex(), payload_json


# ── Contract interaction ──────────────────────────────────────────────────────

def _load_contract_address() -> str:
    try:
        with open(DEPLOYMENT_FILE) as f:
            return json.load(f)["address"]
    except (FileNotFoundError, KeyError) as e:
        raise RuntimeError(
            f"deployment.json not found or missing 'address' key. "
            f"Run: cd on_chain && npx hardhat run scripts/deploy.js --network mantleSepolia"
        ) from e


def submit_to_mantle(result: dict) -> dict:
    """
    Hash the analysis and submit to AuditLog.sol on Mantle Sepolia.
    Returns audit info dict including tx_hash and explorer URL.
    Raises on failure (let run_pipeline.py catch and mark as non-fatal).
    """
    if not PRIVATE_KEY or PRIVATE_KEY == "0x" + "0" * 64:
        raise RuntimeError("PRIVATE_KEY not set in .env — cannot submit to Mantle")

    contract_address = _load_contract_address()
    data_hash_hex, payload_json = compute_hash(result)

    w3 = _get_w3()

    account  = w3.eth.account.from_key(PRIVATE_KEY)
    contract = w3.eth.contract(
        address=Web3.to_checksum_address(contract_address),
        abi=AUDIT_LOG_ABI,
    )

    # Check balance
    balance = w3.eth.get_balance(account.address)
    if balance == 0:
        raise RuntimeError(
            f"Wallet {account.address} has 0 MNT on Mantle Sepolia. "
            f"Get testnet MNT from: https://faucet.sepolia.mantle.xyz"
        )

    # Prepare parameters
    analysis        = result.get("analysis", {})
    symbol          = result["symbol"]
    verdict         = str(analysis.get("verdict", "NEUTRAL"))[:32]
    confidence      = int(min(max(analysis.get("confidence_score", 0), 0), 100))
    confluence_count = int(min(max(analysis.get("confluence_count", 0), 0), 12))
    scenario        = f"S{result.get('scenario_number', 0)}_{result.get('scenario_name', 'UNKNOWN')}"[:64]

    # Convert hash to bytes32
    data_hash_bytes = bytes.fromhex(data_hash_hex[2:] if data_hash_hex.startswith("0x") else data_hash_hex)

    # Build transaction with EIP-1559 pricing + estimated gas limit.
    # estimate_gas accounts for actual calldata size (verdict/scenario strings vary).
    # maxFeePerGas = 2× baseFee + tip ensures inclusion even on moderate congestion.
    nonce    = w3.eth.get_transaction_count(account.address)
    fn_call  = contract.functions.logAnalysis(
        symbol, data_hash_bytes, verdict, confidence, confluence_count, scenario,
    )
    try:
        gas_est = fn_call.estimate_gas({"from": account.address})
        gas_limit = int(gas_est * 1.3)   # 30% buffer on estimate
    except Exception:
        gas_limit = 200_000              # safe fallback for all string lengths

    try:
        latest   = w3.eth.get_block("latest")
        base_fee = latest.get("baseFeePerGas", w3.to_wei("0.001", "gwei"))
        tip      = w3.to_wei("0.001", "gwei")
        max_fee  = base_fee * 2 + tip
        tx = fn_call.build_transaction({
            "from":                 account.address,
            "nonce":                nonce,
            "gas":                  gas_limit,
            "maxFeePerGas":         max_fee,
            "maxPriorityFeePerGas": tip,
        })
    except Exception:
        # Network doesn't support EIP-1559 — fall back to legacy gasPrice
        tx = fn_call.build_transaction({
            "from":     account.address,
            "nonce":    nonce,
            "gas":      gas_limit,
            "gasPrice": int(w3.eth.gas_price * 1.3),
        })

    signed  = account.sign_transaction(tx)
    tx_hash = w3.eth.send_raw_transaction(signed.raw_transaction)

    logger.info(f"[{symbol}] Tx submitted: {tx_hash.hex()} — waiting for confirmation...")
    receipt = w3.eth.wait_for_transaction_receipt(tx_hash, timeout=60)

    if receipt["status"] != 1:
        raise RuntimeError(f"Transaction failed (status=0): {tx_hash.hex()}")

    confirmed_hash = receipt["transactionHash"].hex()
    explorer_url   = f"https://explorer.sepolia.mantle.xyz/tx/{confirmed_hash}"

    logger.info(f"[{symbol}] ✅ On-chain audit confirmed: {explorer_url}")

    # ── Update live oracle state (separate tx, non-fatal) ────────────────────
    # This writes the latest signal to contract state so any Mantle DeFi protocol
    # can call getLatestSignal("BTCUSDT") and read the current AI regime.
    macro_regime = result.get("macro_regime", {}).get("macro_regime", "TRANSITION")
    try:
        oracle_nonce = w3.eth.get_transaction_count(account.address)
        oracle_fn    = contract.functions.updateSignal(
            symbol, verdict, macro_regime, confidence, confluence_count, scenario
        )
        oracle_gas   = 150_000
        try:
            oracle_gas = int(oracle_fn.estimate_gas({"from": account.address}) * 1.3)
        except Exception:
            pass

        oracle_tx = oracle_fn.build_transaction({
            "from":  account.address,
            "nonce": oracle_nonce,
            "gas":   oracle_gas,
            "gasPrice": int(w3.eth.gas_price * 1.3),
        })
        oracle_signed = account.sign_transaction(oracle_tx)
        oracle_hash   = w3.eth.send_raw_transaction(oracle_signed.raw_transaction)
        w3.eth.wait_for_transaction_receipt(oracle_hash, timeout=30)
        logger.info(f"[{symbol}] ✅ Oracle state updated: {oracle_hash.hex()[:16]}...")
    except Exception as e:
        logger.debug(f"[{symbol}] Oracle state update failed (non-fatal): {e}")

    return {
        "audit_tx_hash":      confirmed_hash,
        "audit_explorer_url": explorer_url,
        "audit_block":        receipt["blockNumber"],
        "data_hash":          data_hash_hex,
        "hash_payload_json":  payload_json,
        "contract_address":   contract_address,
    }


# ── Standalone verify ─────────────────────────────────────────────────────────

def verify_hash(result: dict, claimed_hash: str) -> bool:
    """
    Recompute the hash from a result dict and compare to a claimed hash.
    Used by the dashboard "Verify" button to let anyone confirm integrity.
    """
    recomputed, _ = compute_hash(result)
    normalise = lambda h: h.lower().lstrip("0x")
    return normalise(recomputed) == normalise(claimed_hash)


if __name__ == "__main__":
    # Quick test — prints hash without submitting
    import sys
    test_result = {
        "symbol": "BTCUSDT",
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "scenario_number": 1,
        "scenario_name": "HEALTHY_UPTREND",
        "cvd_matrix_state": "BOTH_RISING",
        "macro_regime": {"macro_regime": "BULL"},
        "analysis": {
            "verdict": "STRONG_LONG",
            "confidence_score": 75,
            "confluence_count": 8,
            "entry_trigger": "15m candle close above consolidation high with CVD making new high",
            "stop_price": 44500.0,
            "target_1": 47000.0,
            "leverage_recommended": 7,
            "pre_trade_note_why": "BOTH_RISING CVD matrix + OI rising = genuine accumulation",
            "pre_trade_note_wrong": "If Spot CVD stalls for 3+ candles while price continues higher",
            "pre_trade_note_add": "If OI rises 5%+ with price above breakout and funding <0.07%",
            "failure_mode": "Spot CVD flattening while price rises = distribution beginning",
            "playbook_rules_cited": ["Part 0A: BULL regime", "Part 3: BOTH_RISING", "Part 2: S1 decision tree"],
        },
    }
    h, payload = compute_hash(test_result)
    print(f"Hash:    {h}")
    print(f"Payload: {payload[:200]}...")
    print(f"\nVerify:  {verify_hash(test_result, h)}")
